### ISSUE TITLE
Role prevents execution with tag filter

### ISSUE THREAD

**Issue by kiesel** [andrewrothstein/ansible-docker#13]
Given an Ansible playbook with multiple roles:

```
[...]
- hosts:
    - backend
  roles:
    - role: backend
      tags: backend
    - role: andrewrothstein.docker
      tags: docker
      docker_tls: False
[...]
```

If I execute the whole playbook for certain hosts, execution is successful. If I execute the same playbook with a `--tag` or `-t` filter, then this message appears:

```
TASK [andrewrothstein.docker : configuring package management system]
****************************************************************************
fatal: [be-01.XXXXXXXX]: FAILED! => {"msg": "'docker_installer' is undefined"}
        to retry, use: --limit @/.../ansible/playbook.retry

PLAY RECAP *****************************************************************
be-01.XXXXXXXX : ok=7    changed=0    unreachable=0    failed=1
```

Filtering with the `docker` tag (which in my example the role is indeed assigned to) leads to no error.

Expected state would be that the filtering out does not lead to this error.
